### ISSUE TITLE
`upsun project:init --help` returns fatal error

### ISSUE THREAD

**Issue by tylers-username** [platformsh/platformify#141]
## Steps to reproduce
* Download Upsun vendorized darwin binary
* Copy it to project directory
* Launch: `upsun project:init --help`

## Expected
To see help text

## Actual
See:

```bash
"panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1524d18]

goroutine 1 [running]:
github.com/platformsh/cli/commands.newRootCommand.func4(0xc000005800, {0xc000098190, 0x2, 0x2})
        /Users/akalipetis/Developer/github.com/platformsh/cli/commands/root.go:109 +0x1d8
github.com/spf13/cobra.(*Command).ExecuteC(0xc000004900)
        /Users/akalipetis/Developer/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1049 +0x54a
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/akalipetis/Developer/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        /Users/akalipetis/Developer/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:961
github.com/platformsh/cli/commands.Execute(0xc000156900)
        /Users/akalipetis/Developer/github.com/platformsh/cli/commands/root.go:38 +0x23f
main.main()
        /Users/akalipetis/Developer/github.com/platformsh/cli/cmd/platform/main.go:36 +0x1cf"
```

**Comment by akalipetis** [comment]
This has been resolved in https://github.com/platformsh/cli/pull/123
